### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dennis-kurochkin** [dennis-kurochkin/google-calendar-link-generator#1]
- [ ] Set up a projects
- [ ] Add basic layout
- [ ] Add form
- [ ] Add link generation
- [ ] Enhance layout, add credentials

**Comment by dennis-kurochkin** [comment]
Useful links:
- https://decomaan.github.io/google-calendar-link-generator/ 
- https://useroffline.blogspot.com/2009/06/making-google-calendar-link.html
